remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme 
title: SpicyPy Project
description: >-
  This page provides a tutorial on how to implement multiple scenarios in
  SpicyPy including frame transformation, ground-station contact times,
  and orbit propagations using existing kernels. This project was created
  as a final project for MAE-6540 Advanced Astrodynamics at Utah State
  University.

  


